# Generated by Django 3.1.3 on 2020-12-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201126_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
