# Generated by Django 3.1.3 on 2020-11-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='name',
        ),
    ]
