# Generated by Django 3.1.3 on 2020-11-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20201127_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dimension',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Единицы измерения'),
        ),
    ]
