# Generated by Django 3.1.3 on 2020-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20201127_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dimension',
            field=models.CharField(max_length=10, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
    ]
