# Generated by Django 3.1.3 on 2020-11-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.CharField(choices=[('завтрак', 'Завтрак'), ('обед', 'Обед'), ('ужин', 'Ужин')], default='завтрак', max_length=50, verbose_name='Тег'),
        ),
    ]
