# Generated by Django 3.1.3 on 2020-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201126_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тег')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
    ]
