# Generated by Django 3.1.3 on 2020-12-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_auto_20201206_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('---', 'Default'), ('orange', 'Orange'), ('green', 'Green'), ('purple', 'Purple')], default='---', max_length=10, verbose_name='Цвет'),
        ),
    ]
