# Generated by Django 3.1.3 on 2020-12-10 18:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0023_auto_20201210_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipefavorite',
            unique_together={('user', 'recipe')},
        ),
    ]
